[colors.bright]
black = "0x002b36"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[colors.normal]
black = "0x073642"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[colors.primary]
background = "0x002b36"
foreground = "0x839496"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font.normal]
family = "DejaVu Sans Mono"
style = "Regular"

[font]
size = 11.0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[shell]
args = ["-c", "if [ -z $SWAYSOCK -a \"$XDG_SESSION_DESKTOP\" != 'i3' ]; then tmux attach -t alac || tmux new -s alac; else zsh -l; fi"]
program = "/bin/zsh"

[window]
startup_mode = "Maximized"
